spring:
  datasource:
#    initialization-mode: always
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test-db
    # tcp connection jdbc:h2:tcp://localhost:5656/mem:test-db
    # web connection http://localhost:6565
    username: sa
    password:
  jpa:
#    generate-ddl: true
    hibernate:
      ddl-auto: create
