spring:
  profiles.active: default
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3432/testdb
    username: user
    password: password

logging:
  level:
    org.springframework: warn
#    org.springframework.test.context.transaction.TransactionContext: trace
